#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d     
# bspc config top_padding       20

bspc config border_width             3
bspc config window_gap               5
bspc config normal_border_color      "#0d24f6"
bspc config focused_border_color     "#a732fb"
bspc config active_border_color      "#00ff49"
bspc config preset_border_color      "#ff1cdd"

bspc config split_ratio              0.48
bspc config borderless_monocle       true
bspc config gapless_monocle          true

bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom -f &

xrandr --output Virtual1 --mode 1360x768 &

 $HOME/.config/polybar/launch.sh &

#eww open bar

nitrogen --restore

